In [1]:
#Dataset belongs to UCI but downloaded from Kaggle 
#Link: https://www.kaggle.com/ritesaluja/bank-note-authentication-uci-data

#importing required libraries
import pandas as pd
import numpy as np
#for splitting dataset into testing and training
from sklearn.model_selection import train_test_split

In [6]:
#datset path
df=pd.read_csv('BankNote_Authentication.csv')
df.head()

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [7]:
#Independent and Dependent features
X=df.iloc[:,:-1] #Features
y=df.iloc[:,-1] #identifying feature(class)

In [15]:
X.head(20)

    variance  skewness  curtosis  entropy
0    3.62160    8.6661  -2.80730 -0.44699
1    4.54590    8.1674  -2.45860 -1.46210
2    3.86600   -2.6383   1.92420  0.10645
3    3.45660    9.5228  -4.01120 -3.59440
4    0.32924   -4.4552   4.57180 -0.98880
5    4.36840    9.6718  -3.96060 -3.16250
6    3.59120    3.0129   0.72888  0.56421
7    2.09220   -6.8100   8.46360 -0.60216
8    3.20320    5.7588  -0.75345 -0.61251
9    1.53560    9.1772  -2.27180 -0.73535
10   1.22470    8.7779  -2.21350 -0.80647
11   3.98990   -2.7066   2.39460  0.86291
12   1.89930    7.6625   0.15394 -3.11080
13  -1.57680   10.8430   2.54620 -2.93620
14   3.40400    8.7261  -2.99150 -0.57242
15   4.67650   -3.3895   3.48960  1.47710
16   2.67190    3.0646   0.37158  0.58619
17   0.80355    2.8473   4.34390  0.60170
18   1.44790   -4.8794   8.34280 -2.10860
19   5.24230   11.0272  -4.35300 -4.10130

In [11]:
y.head(20)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: class, dtype: int64

In [ ]:
### Train Test Split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
### Implement Random Forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

In [ ]:
## Prediction
y_pred=classifier.predict(X_test)

In [ ]:

### Check Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
print(score)

In [ ]:

### Create a Pickle file using serialization 
import pickle
pickle_out = open("classifier.pkl","wb")
pickle.dump(classifier, pickle_out)
pickle_out.close()

In [ ]:

classifier.predict([[2,3,4,1]])